# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Danilo Abbasciano <danilo@piumalab.org>
"""A corpus of signed artifacts — most of them broken on purpose.

Roundtrip tests prove the signer works. This corpus is the other half: every
way a signature can fail that Sigillum claims to detect, in one place, each
with the verdict the verifier is expected to reach. A verifier earns trust by
saying *no* to the right things, and each entry here is a "no" (or a
deliberate "yes" that must not become a false alarm).

The artifacts are generated rather than committed: certificates expire, and a
corpus that has to be regenerated by hand rots. Everything derives from the
in-process test PKI in `fixtures.py`, so the corpus is reproducible from
source and never needs the network.

Two ways to use it:

  - `tests/test_vectors.py` asserts each vector's expected verdict;
  - `python3 tests/vectors.py --out DIR` materialises it on disk (with the
    trust anchors and a README) so the same files can be fed to Dike, Adobe
    Acrobat, the EU DSS demo validator, or `sigillum verify` by hand — the
    interesting question being whether other tools agree.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.x509 import ocsp as crypto_ocsp

from fixtures import (
    TestChain,
    make_minimal_pdf,
    make_p12_from_chain,
    make_test_chain,
)
from sigillum.core.credentials import FileProvider
from sigillum.core.lt import add_lt_attributes
from sigillum.core.pades_lt import add_dss
from sigillum.core.signer import (
    CAdESSigner,
    PAdESSigner,
    SignatureLevel,
    SignOptions,
    XAdESSigner,
)

SAMPLE_XML = b"""<?xml version="1.0" encoding="UTF-8"?>
<Fattura>
  <Numero>42</Numero>
  <Importo valuta="EUR">199.90</Importo>
</Fattura>
"""

# An incremental update that adds a page: an ordinary document edit, appended
# after the signed byte ranges.
APPENDED_EDIT = (
    b"\n90 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>\nendobj\n"
    b"xref\n0 0\ntrailer\n<< /Size 91 /Root 1 0 R >>\nstartxref\n0\n%%EOF\n"
)


@dataclass(frozen=True)
class Expect:
    """The verdict a vector must produce. `None` means "not asserted"."""
    all_valid: bool
    signers: int = 1
    hash_valid: bool | None = None
    signature_valid: bool | None = None
    cert_trusted: bool | None = None
    revocation: str | None = None          # RevocationStatus value
    revoked: bool | None = None
    coverage_whole_file: bool | None = None
    coverage_modified: bool | None = None
    document_errors: bool | None = None    # errors on the result, not per-signer


@dataclass
class Vector:
    vid: str
    description: str
    fmt: str                     # pades | cades | xades
    path: Path
    expect: Expect
    trust: str = "ca"            # key into Corpus.trust_stores
    original: Path | None = None

    @property
    def why(self) -> str:
        return f"{self.vid}: {self.description}"


@dataclass
class Corpus:
    root: Path
    chain: TestChain
    intruder: TestChain
    vectors: list[Vector] = field(default_factory=list)

    def trust_store(self, key: str) -> list[x509.Certificate]:
        if key == "ca":
            return [self.chain.ca_cert]
        if key == "intruder":
            return [self.intruder.ca_cert]
        if key == "none":
            return []
        raise KeyError(key)

    def by_id(self, vid: str) -> Vector:
        for vector in self.vectors:
            if vector.vid == vid:
                return vector
        raise KeyError(vid)


def ocsp_response(
    target: x509.Certificate,
    issuer: x509.Certificate,
    issuer_key,
    *,
    status=crypto_ocsp.OCSPCertStatus.GOOD,
    revoked_at: datetime | None = None,
    reason: x509.ReasonFlags | None = None,
    responder: x509.Certificate | None = None,
    responder_key=None,
) -> bytes:
    """A DER OCSPResponse about `target`, signed by the issuer unless told otherwise."""
    builder = crypto_ocsp.OCSPResponseBuilder().add_response(
        cert=target,
        issuer=issuer,
        algorithm=hashes.SHA256(),
        cert_status=status,
        this_update=datetime.now(timezone.utc) - timedelta(minutes=1),
        next_update=datetime.now(timezone.utc) + timedelta(days=1),
        revocation_time=revoked_at,
        revocation_reason=reason,
    )
    builder = builder.responder_id(
        crypto_ocsp.OCSPResponderEncoding.HASH, responder or issuer)
    return builder.sign(
        responder_key or issuer_key, hashes.SHA256(),
    ).public_bytes(serialization.Encoding.DER)


def build_corpus(root: Path) -> Corpus:
    """Generate every vector under `root`, one directory each."""
    root.mkdir(parents=True, exist_ok=True)
    chain = make_test_chain()
    intruder = make_test_chain()
    corpus = Corpus(root=root, chain=chain, intruder=intruder)

    trust = root / "trust"
    trust.mkdir(exist_ok=True)
    (trust / "ca.pem").write_bytes(
        chain.ca_cert.public_bytes(serialization.Encoding.PEM))
    (trust / "intruder-ca.pem").write_bytes(
        intruder.ca_cert.public_bytes(serialization.Encoding.PEM))

    work = root / ".work"
    work.mkdir(exist_ok=True)
    p12_path = work / "signer.p12"
    p12_path.write_bytes(make_p12_from_chain(chain, password="test"))
    provider = FileProvider(p12_path)
    credential = provider.unlock(provider.list_certificates()[0].id, "test")

    def emit(vid: str, filename: str, data: bytes) -> Path:
        target = root / vid
        target.mkdir(exist_ok=True)
        path = target / filename
        path.write_bytes(data)
        return path

    def add(vector: Vector) -> None:
        corpus.vectors.append(vector)

    # --- source documents -------------------------------------------------
    source_pdf = work / "document.pdf"
    source_pdf.write_bytes(make_minimal_pdf())
    source_xml = work / "fattura.xml"
    source_xml.write_bytes(SAMPLE_XML)

    def sign_pdf(name: str, src: Path, **kwargs) -> bytes:
        out = work / name
        PAdESSigner().sign(
            input_path=src, output_path=out, credential=credential,
            options=SignOptions(level=SignatureLevel.B, **kwargs),
        )
        return out.read_bytes()

    signed_pdf = sign_pdf("signed.pdf", source_pdf, reason="Vector corpus")

    # --- PAdES ------------------------------------------------------------
    add(Vector(
        vid="001-pades-valid",
        description="a plain B-level PAdES signature, trusted root",
        fmt="pades",
        path=emit("001-pades-valid", "document.pdf", signed_pdf),
        expect=Expect(
            all_valid=True, hash_valid=True, signature_valid=True,
            cert_trusted=True, coverage_whole_file=True, revocation="not-checked",
        ),
    ))

    # A byte changed *inside* the signed range: the message digest no longer
    # matches, which is the hash check's job rather than the coverage check's.
    altered = signed_pdf.replace(
        b"/MediaBox [0 0 612 792]", b"/MediaBox [0 0 613 792]", 1)
    assert len(altered) == len(signed_pdf), "the edit must not shift offsets"
    assert altered != signed_pdf
    add(Vector(
        vid="002-pades-altered",
        description="page geometry edited inside the signed range",
        fmt="pades",
        path=emit("002-pades-altered", "document.pdf", altered),
        expect=Expect(
            all_valid=False, hash_valid=False, signature_valid=True,
            cert_trusted=True, coverage_whole_file=True,
        ),
    ))

    add(Vector(
        vid="003-pades-untrusted-root",
        description="valid signature, but the CA is not in the trust store",
        fmt="pades",
        path=emit("003-pades-untrusted-root", "document.pdf", signed_pdf),
        trust="intruder",
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=False, coverage_whole_file=True,
        ),
    ))

    add(Vector(
        vid="004-pades-incremental-update",
        description="a page appended after signing: signature intact, document changed",
        fmt="pades",
        path=emit("004-pades-incremental-update", "document.pdf",
                  signed_pdf + APPENDED_EDIT),
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=True, coverage_whole_file=False,
            coverage_modified=True, document_errors=True,
        ),
    ))

    good_ocsp = ocsp_response(chain.signer_cert, chain.ca_cert, chain.ca_key)
    lt_pdf = add_dss(
        signed_pdf,
        certificates=[chain.signer_cert, chain.ca_cert],
        ocsp_responses=[good_ocsp],
    )
    add(Vector(
        vid="005-pades-lt-dss",
        description="LT: a DSS appended after signing — validation data, not tampering",
        fmt="pades",
        path=emit("005-pades-lt-dss", "document.pdf", lt_pdf),
        expect=Expect(
            all_valid=True, hash_valid=True, signature_valid=True,
            cert_trusted=True, revocation="good", revoked=False,
            coverage_whole_file=False, coverage_modified=False,
            document_errors=False,
        ),
    ))

    revoked_pdf = add_dss(
        signed_pdf,
        certificates=[chain.ca_cert],
        ocsp_responses=[ocsp_response(
            chain.signer_cert, chain.ca_cert, chain.ca_key,
            status=crypto_ocsp.OCSPCertStatus.REVOKED,
            revoked_at=datetime.now(timezone.utc) - timedelta(days=2),
            reason=x509.ReasonFlags.key_compromise,
        )],
    )
    add(Vector(
        vid="006-pades-revoked-key-compromise",
        description="embedded OCSP says the signer key was compromised",
        fmt="pades",
        path=emit("006-pades-revoked-key-compromise", "document.pdf", revoked_pdf),
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=True, revocation="revoked", revoked=True,
            coverage_modified=False,
        ),
    ))

    add(Vector(
        vid="007-pades-edit-after-dss",
        description="an edit hiding behind a legitimate DSS update",
        fmt="pades",
        path=emit("007-pades-edit-after-dss", "document.pdf",
                  lt_pdf + APPENDED_EDIT),
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=True, coverage_modified=True, document_errors=True,
        ),
    ))

    forged_pdf = add_dss(
        signed_pdf,
        certificates=[chain.ca_cert],
        ocsp_responses=[ocsp_response(
            chain.signer_cert, chain.ca_cert, chain.ca_key,
            responder=intruder.ca_cert, responder_key=intruder.ca_key,
        )],
    )
    add(Vector(
        vid="008-pades-forged-ocsp",
        description="embedded OCSP signed by a CA with no authority over this cert",
        fmt="pades",
        path=emit("008-pades-forged-ocsp", "document.pdf", forged_pdf),
        expect=Expect(
            # Not revoked, but not vouched for either: unavailable, never good.
            all_valid=True, cert_trusted=True,
            revocation="unavailable", revoked=False,
        ),
    ))

    first = work / "one-signature.pdf"
    first.write_bytes(signed_pdf)
    two_signatures = sign_pdf("two-signatures.pdf", first, reason="Second signer")
    add(Vector(
        vid="009-pades-two-signatures",
        description="two sequential signatures: the second update is legitimate",
        fmt="pades",
        path=emit("009-pades-two-signatures", "document.pdf", two_signatures),
        expect=Expect(
            all_valid=True, signers=2, hash_valid=True, signature_valid=True,
            cert_trusted=True, coverage_whole_file=True, document_errors=False,
        ),
    ))

    add(Vector(
        vid="010-pades-unsigned",
        description="a PDF carrying no signature at all",
        fmt="pades",
        path=emit("010-pades-unsigned", "document.pdf", make_minimal_pdf()),
        expect=Expect(all_valid=False, signers=0),
    ))

    # --- CAdES ------------------------------------------------------------
    p7m_out = work / "document.pdf.p7m"
    CAdESSigner().sign(
        input_path=source_pdf, output_path=p7m_out, credential=credential,
        options=SignOptions(level=SignatureLevel.B),
    )
    signed_p7m = p7m_out.read_bytes()

    add(Vector(
        vid="011-cades-valid",
        description="an enveloping .p7m, trusted root",
        fmt="cades",
        path=emit("011-cades-valid", "document.pdf.p7m", signed_p7m),
        expect=Expect(
            all_valid=True, hash_valid=True, signature_valid=True,
            cert_trusted=True, revocation="not-checked",
        ),
    ))

    altered_p7m = signed_p7m.replace(
        b"/MediaBox [0 0 612 792]", b"/MediaBox [0 0 613 792]", 1)
    assert len(altered_p7m) == len(signed_p7m)
    assert altered_p7m != signed_p7m
    add(Vector(
        vid="012-cades-altered",
        description="the document enveloped in the .p7m was edited",
        fmt="cades",
        path=emit("012-cades-altered", "document.pdf.p7m", altered_p7m),
        expect=Expect(
            all_valid=False, hash_valid=False, signature_valid=True,
            cert_trusted=True,
        ),
    ))

    add(Vector(
        vid="013-cades-untrusted-root",
        description="valid .p7m, CA outside the trust store",
        fmt="cades",
        path=emit("013-cades-untrusted-root", "document.pdf.p7m", signed_p7m),
        trust="none",
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=False,
        ),
    ))

    revoked_p7m = add_lt_attributes(
        signed_p7m,
        certificates=[chain.ca_cert],
        ocsp_responses=[ocsp_response(
            chain.signer_cert, chain.ca_cert, chain.ca_key,
            status=crypto_ocsp.OCSPCertStatus.REVOKED,
            revoked_at=datetime.now(timezone.utc) - timedelta(days=1),
            reason=x509.ReasonFlags.key_compromise,
        )],
    )
    add(Vector(
        vid="014-cades-revoked-key-compromise",
        description="RevocationValues in the .p7m report a compromised key",
        fmt="cades",
        path=emit("014-cades-revoked-key-compromise", "document.pdf.p7m", revoked_p7m),
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=True, revocation="revoked", revoked=True,
        ),
    ))

    # --- XAdES ------------------------------------------------------------
    xml_out = work / "fattura-signed.xml"
    XAdESSigner().sign(
        input_path=source_xml, output_path=xml_out, credential=credential,
        options=SignOptions(level=SignatureLevel.B),
    )
    signed_xml = xml_out.read_bytes()

    add(Vector(
        vid="015-xades-valid",
        description="an enveloped XAdES signature, trusted root",
        fmt="xades",
        path=emit("015-xades-valid", "fattura.xml", signed_xml),
        expect=Expect(
            all_valid=True, hash_valid=True, signature_valid=True,
            cert_trusted=True,
        ),
    ))

    altered_xml = signed_xml.replace(b"199.90", b"199.91", 1)
    assert altered_xml != signed_xml
    add(Vector(
        vid="016-xades-altered",
        description="the invoice amount was changed after signing",
        fmt="xades",
        path=emit("016-xades-altered", "fattura.xml", altered_xml),
        expect=Expect(
            all_valid=False, hash_valid=False, signature_valid=True,
            cert_trusted=True,
        ),
    ))

    add(Vector(
        vid="017-xades-untrusted-root",
        description="valid XAdES signature, CA outside the trust store",
        fmt="xades",
        path=emit("017-xades-untrusted-root", "fattura.xml", signed_xml),
        trust="none",
        expect=Expect(
            all_valid=False, hash_valid=True, signature_valid=True,
            cert_trusted=False,
        ),
    ))

    return corpus


def write_readme(corpus: Corpus) -> Path:
    """A README next to the artifacts, so a dumped corpus explains itself."""
    lines = [
        "# Sigillum verification vectors",
        "",
        "Generated by `python3 tests/vectors.py --out .` — every artifact is",
        "signed by the throwaway CA in `trust/ca.pem`, which is also the only",
        "trust anchor needed to check them. `trust/intruder-ca.pem` is a second,",
        "unrelated CA used by the vectors that test a wrong trust anchor.",
        "",
        "Verify one by hand:",
        "",
        "```bash",
        "sigillum verify 001-pades-valid/document.pdf --trusted trust/ca.pem",
        "```",
        "",
        "`.work/` holds the intermediates, including the throwaway signer",
        "`signer.p12` (password `test`), for building variants of a vector.",
        "",
        "| Vector | Format | Trust anchor | Expected |",
        "|---|---|---|---|",
    ]
    for vector in corpus.vectors:
        expected = "valid" if vector.expect.all_valid else "**rejected**"
        detail = vector.description
        anchor = {"ca": "trust/ca.pem", "intruder": "trust/intruder-ca.pem",
                  "none": "(none)"}[vector.trust]
        lines.append(
            f"| `{vector.vid}` | {vector.fmt.upper()} | {anchor} | "
            f"{expected} — {detail} |")
    lines.append("")
    path = corpus.root / "README.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", required=True,
                        help="directory to write the corpus into")
    args = parser.parse_args(argv)

    root = Path(args.out).expanduser().resolve()
    corpus = build_corpus(root)
    write_readme(corpus)
    for vector in corpus.vectors:
        verdict = "valid" if vector.expect.all_valid else "rejected"
        print(f"{vector.vid:34} {verdict:9} {vector.path.relative_to(root)}")
    print(f"\n{len(corpus.vectors)} vectors in {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
