packaging/flatpak/io.github.sigillum.desktop      usr/share/applications
packaging/flatpak/io.github.sigillum.metainfo.xml usr/share/metainfo
packaging/flatpak/io.github.sigillum.svg          usr/share/icons/hicolor/scalable/apps
completion/bash/sigillum                          usr/share/bash-completion/completions
completion/zsh/_sigillum                          usr/share/zsh/vendor-completions
